app: craft-glud
ssh_url: craft-glud@deploy.us1.frbit.com
git_remote: craft-glud/master
before:
    code/up: {  }
after:
    code/down:
        - 'php craft migrate/all'
        - 'php craft project-config/apply'
