fieldLayouts:
  197c45d7-abdb-4524-94f9-98a0627a0bd2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9bd3ace2-f868-4fc9-b726-ed9d3940c04d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e9bb13fe-88c7-4929-a873-4f2ff3009c84 # Image One
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7654f8bf-c99c-4e1e-94a4-4daae153262e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1058d120-1961-4fab-b32d-9d66766c6da3 # Image Two
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ecd723f-2e19-465a-ab30-69771b130e67
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6bc4874b-15d4-4dc6-badc-0042333f9456
        userCondition: null
handle: about
hasTitleField: false
name: About
section: dd1ba317-6b54-4198-9609-cab49a5b6544 # About
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
