fieldLayouts:
  0ee2e9df-3e39-4085-93f5-c6e2b6b333a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 23c107a4-572d-4c03-8cb7-35bd6452d0c2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bf5da3bd-efd8-4b0b-bf7f-c6407734b0cc
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 07008e02-86c4-47b8-a96a-8c9e6cef77d5 # thanks-test
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
