fieldLayouts:
  e743476b-472e-4feb-93ca-53cfbb6e9968:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Blog Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 61a9f16f-8f5c-44f8-b3d8-7135d2cf76a2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc624c9f-1d69-4ac8-9589-6abc8cead3f0 # Blog Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a8346fc-35e0-46d3-8ded-58d3bc39c802
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 939a82ed-ad48-4e83-b71a-0f3012f6369f # Author name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fff0ca7c-1749-4c68-9229-79de654097bc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a6b0622f-f24c-4f99-9b6a-64b9b74f2fb9 # Author Profile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: daa30c5d-5e42-4271-b84f-9e64529fcd2c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f508bf38-b99b-43d4-b1de-57e0434a7056 # Publish date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2562f003-1d19-474c-9e12-65de69b2e887
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 48527bb6-858e-4858-b159-48ff4f9ffc9b # Media Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca2458b2-144c-425b-b0ce-5b5b0d7438f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3515d6db-6243-4d34-a80a-574f694254f1 # Media Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00dc75c7-1d93-473f-9a47-2f042ed85d29
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2a68880a-68ad-475d-a31d-b44a4cead789 # Media Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aa2657d-d0dd-432d-b6ad-afffaff90ea3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d4ddb970-bf7f-48ac-9ef2-fc033b62cef5
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 3733d377-59f7-40d4-a946-80540df385ab # Blog
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
