fieldLayouts:
  ece41be4-ad70-455e-a518-a8b76f76e0b6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cf74fe0b-aa60-432d-bf51-3d6e93fdd9f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e9bb13fe-88c7-4929-a873-4f2ff3009c84 # Image One
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8000d59-a98f-41bb-905b-6ea917ae7a91
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1058d120-1961-4fab-b32d-9d66766c6da3 # Image Two
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25ddedcc-48a4-4e7a-8195-c748b7014446
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68fc520a-f388-4099-babf-5bb9189d80f4
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: fe980643-d3a8-4b2f-86a8-3027e9afb617 # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
