columnSuffix: tgumzdxk
contentColumnType: string(255)
fieldGroup: c804936a-0498-4a5c-b0f5-2b2c8ddc1c55 # careers
handle: buttonLink
instructions: null
name: 'Button Link'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
