columnSuffix: hxccknve
contentColumnType: text
fieldGroup: fda1e4ba-87a0-4b92-a3d5-00bec5715df4 # Residential
handle: heroText
instructions: null
name: 'Hero Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
