columnSuffix: zdonpirv
contentColumnType: text
fieldGroup: b3f7bc1f-9046-40ec-9b7d-b8aa4e0ece45 # Media
handle: mediaContent
instructions: null
name: 'Media Content'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 4bb2c9ad-a323-449d-b735-12979f6ae443 # Blogs
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
