columnSuffix: wggzmzzp
contentColumnType: datetime
fieldGroup: b3f7bc1f-9046-40ec-9b7d-b8aa4e0ece45 # Media
handle: publishDate
instructions: null
name: 'Publish date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
