defaultPlacement: end
enableVersioning: true
handle: careers
name: Careers
propagationMethod: all
siteSettings:
  066dea4a-eb24-4ccd-adb4-07aace1d6c2b: # Get Amped Electrical
    enabledByDefault: true
    hasUrls: true
    template: careers/_entry
    uriFormat: 'careers/{slug}'
type: channel
