defaultPlacement: end
enableVersioning: true
handle: residential
name: Residential
propagationMethod: all
siteSettings:
  066dea4a-eb24-4ccd-adb4-07aace1d6c2b: # Get Amped Electrical
    enabledByDefault: true
    hasUrls: true
    template: residential/_entry
    uriFormat: 'residential/{slug}'
type: channel
